server:
  port: 8080

spring:
    application:
      name: dev-web
    datasource:
      master:
        url: jdbc:mysql://47.106.212.169:3307/test?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        username: root
        password: root
        driver_class_namel: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
      slave1:
        url: jdbc:mysql://47.106.212.169:3308/test?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        username: onlyselect
        password: 123456
        driver_class_namel: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
      slave2:
        url: jdbc:mysql://47.106.212.169:3309/test?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        username: onlyselect
        password: 123456
        driver_class_namel: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
    redis:
        host: 47.106.212.169
        password: root
        port: 6379
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1
    rabbitmq:
        host: 47.106.212.169
        port: 5672
        username: guest
        password: guest
    profiles:
        active: dev
eureka:
  client:
        service-url:
            defaultZone:  http://47.106.212.169:8761/eureka/
        enabled: true
            #���ڸ�Ӧ��Ϊע������,��������Ϊfalse,������ע������ע���Լ�
        registerWithEureka: true
                   #����ע�����ĵ�ְ�����ά������ʵ��,��������Ҫȥ��������,����Ҳ����Ϊfalse
        fetchRegistry: true
  instance:
        lease-renewal-interval-in-seconds: 5      # ����ʱ�䣬��������Լ���ʱ�䣨ȱʡΪ30s��
        lease-expiration-duration-in-seconds: 15  # ����ʱ�䣬��������Լ����ʱ�䣨ȱʡΪ90s��
        instance-id: ${spring.application.name}
        prefer-ip-address: true
  healthcheck:
        enabled: true # ����������飨����spring-boot-starter-actuator��
mybatis-plus:
    mapperLocation : classpath:/com/boot/demo/mapper/*Mapper.xml
    # ?????src/main/java??? classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # ?????resource?? classpath:/mapper/*Mapper.xml
      #mapper-locations: classpath:mapping/*.xml
      mapper-locations: classpath:/com/boot/demo/mapper/*Mapper.xml
       #???????package?????????
      type-aliases-package: com.boot.demo.entity
      global-config:
      #????  0:"???ID??", 1:"????ID",2:"????ID (??????ID)", 3:"????ID UUID";
        id-type: 2
      #???? 0:"????",1:"? NULL ??"),2:"????"
        field-strategy: 2
      #???????
        db-column-underline: true
      #mp2.3+ ????? mp_
      #table-prefix: mp_
      #??mapper ????
      #refresh-mapper: true
      #??????????
      #capital-mode: true
      # Sequence?????????
        key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #?????????3????
        logic-delete-value: 1
        logic-not-delete-value: 0
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #???????????
        #meta-object-handler: com.baomidou.spring.boot.MyMetaObjectHandler
      configuration:
      #???????(column?????&&??java???????)???????as???????SQL???as? select user_id as userId?
        map-underscore-to-camel-case: true
        cache-enabled: false
      #??JdbcTypeForNull, oracle???????
        jdbc-type-for-null: 'null'

#pagehelper????
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


---
spring:
  profiles: dev
logging:
  config: classpath:logConfig/logback-dev.xml
---
spring:
  profiles: prd
logging:
  config: classpath:logConfig/logback-prd.xml




