server:
  port: 8080

spring:
    application:
      name: dev-web
    datasource:
      master:
        url: jdbc:mysql://47.106.212.169:3307/test?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        username: root
        password: root
        driver_class_namel: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
      slave1:
        url: jdbc:mysql://47.106.212.169:3308/test?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        username: onlyselect
        password: 123456
        driver_class_namel: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true
      slave2:
        url: jdbc:mysql://47.106.212.169:3309/test?useUnicode=true&amp;characterEncoding=utf8&amp;emptyStringsConvertToZero=true
        username: onlyselect
        password: 123456
        driver_class_namel: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 600
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        poolPreparedStatements: true

    redis:
        cluster:
          max-redirects: 6
          nodes:
            47.106.212.169:9001,
            47.106.212.169:9002,
            47.106.212.169:9003,
            47.106.212.169:9004,
            47.106.212.169:9005,
            47.106.212.169:9006
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1

    rabbitmq:
        host: 47.106.212.169
        port: 5672
        username: guest
        password: guest


    profiles:
        active: dev


eureka:
  client:
        service-url:
            defaultZone:  http://47.106.212.169:8761/eureka/
        enabled: true
        registerWithEureka: true
        fetchRegistry: true
  instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
        instance-id: ${spring.application.name}
        prefer-ip-address: true
  healthcheck:
        enabled: true


mybatis-plus:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.boot.demo.entity
      global-config:
        id-type: 2
        field-strategy: 2
        db-column-underline: true
        key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
        logic-delete-value: 1
        logic-not-delete-value: 0
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        jdbc-type-for-null: 'null'

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


---
spring:
  profiles: dev
logging:
  config: classpath:logConfig/logback-dev.xml
---
spring:
  profiles: prd
logging:
  config: classpath:logConfig/logback-prd.xml




