server:
  port: 8080

spring:
    datasource:
        name: demo
        url: jdbc:mysql://47.106.212.169:3306/demo
        username: root
        password: root
        # ??druid???
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        host: 47.106.212.169
        password: root
        port: 6379
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1
    rabbitmq:
        host: 47.106.212.169
        port: 5672
        username: guest
        password: guest
    profiles:
        active: dev

mybatis-plus:
    # ?????src/main/java??? classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # ?????resource?? classpath:/mapper/*Mapper.xml
      #mapper-locations: classpath:mapping/*.xml
      mapper-locations: classpath:/com/boot/demo/mapper/*Mapper.xml
       #???????package?????????
      type-aliases-package: com.boot.demo.entity
      global-config:
      #????  0:"???ID??", 1:"????ID",2:"????ID (??????ID)", 3:"????ID UUID";
        id-type: 2
      #???? 0:"????",1:"? NULL ??"),2:"????"
        field-strategy: 2
      #???????
        db-column-underline: true
      #mp2.3+ ????? mp_
      #table-prefix: mp_
      #??mapper ????
      #refresh-mapper: true
      #??????????
      #capital-mode: true
      # Sequence?????????
        key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #?????????3????
        logic-delete-value: 1
        logic-not-delete-value: 0
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      #???????????
        #meta-object-handler: com.baomidou.spring.boot.MyMetaObjectHandler
      configuration:
      #???????(column?????&&??java???????)???????as???????SQL???as? select user_id as userId?
        map-underscore-to-camel-case: true
        cache-enabled: false
      #??JdbcTypeForNull, oracle???????
        jdbc-type-for-null: 'null'

#pagehelper????
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


---
spring:
  profiles: dev
logging:
  config: classpath:logConfig/logback-dev.xml
---
spring:
  profiles: prd
logging:
  config: classpath:logConfig/logback-prd.xml




